"""CHARACTER_MASTER_PLAN Part 8 / D49 — the START SCENE for the sculpting stage.

WHAT THIS IS FOR. D49 makes the professional showcase model a dedicated,
collaborative stage: import open-source material, sculpt the agent and the
clothing. This builds the .blend that stage opens, so it spends its time on art
instead of on setup — and, more importantly, so every constraint that is already
RATIFIED is present in the viewport as geometry rather than as something someone
has to remember from a document.

WHAT IT CARRIES, and why each one is in the file rather than in a spec:

  RIG          the verified 20-bone T-pose armature and the seven §4.3 sockets,
               generated by p1_agent_model.py — not a copy. D48 says the
               skeleton survives and the art is replaced, so the skeleton is the
               thing the sculpt must fit, and it has to be present to be fitted.
  BLOCKING     the current Part 1 body, locked and unselectable. A shape to work
               against and overwrite, never to accidentally sculpt.
  SCALE        a voxel ruler in 0.20 m bands to 3.20 m, the SLICE and ROOM lines,
               a 1.60 m GU footprint on the floor, and marks at the standing,
               crouched and prone heights. §4.7's numbers are settled and
               measured; a sculptor should be able to see them, not recall them.
  CAMERAS      CAM_GAME at the bake convention (elevation 30 / azimuth 45 —
               D26: a different angle breaks the runtime light maths silently),
               plus front / side / back orthographics.

THE RENDER IS SET TO SHIP SIZE ON PURPOSE. 132x196 px, from CAM_GAME, so F12 is
a one-key reality check at the size the player actually sees (§4.7: 9.8 voxels x
VOXEL_STEP_PX 20). The viewport stays as large as the sculptor wants; the render
is the truth. S1 paid for this lesson on 2026-08-14 — six compression variants
were obvious at 8x and indistinguishable at real size.

⚠️ ONE DISCREPANCY THE SCENE MAKES VISIBLE RATHER THAN HIDES. §4.7 records
standing-including-fedora at 9.8 voxels / 1.96 m, but that figure was MEASURED
off the S2 mockup, whose hat perched above the skull. Part 1's fedora sits ON the
head, anatomically, and the figure measures 1.898 m. The load-bearing numbers are
unaffected and exact: 1 voxel = 0.20 m, and the BODY is 1.80 m = 9.0 voxels. The
9.8 was a hat, not a constraint. Both lines are drawn and labelled so the sculpt
can settle the hat's height deliberately instead of inheriting it.

Run:
  /Applications/Blender.app/Contents/MacOS/Blender --background \\
    --python tools/asset_generation/p8_sculpt_start_scene.py

Then open:
  ASSETS/ISOMETRIC/source_assets/imported_models/agent/agent_sculpt_start.blend
"""

import math
import os
import sys

import bpy
from mathutils import Vector

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import p1_agent_model as base   # noqa: E402  (needs the path above)

OUT_DIR = os.path.join(base.REPO_ROOT, "ASSETS", "ISOMETRIC", "source_assets",
                       "imported_models", "agent")
OUT_BLEND = os.path.join(OUT_DIR, "agent_sculpt_start.blend")

VOXEL_M = 0.20                 # §4.7, settled and measured
SLICE_VOXELS = 8               # LEVELS_PER_STOREY
GU_M = SLICE_VOXELS * VOXEL_M  # 1.60 m — also VOXELS_PER_UNIT_AXIS x voxel
ROOM_M = GU_M * 2.0            # §4.7b: a ROOM is two slices

SHIP_PX = 196                  # 9.8 voxels x VOXEL_STEP_PX 20
GAME_ELEV, GAME_AZIM = 30.0, 45.0

REF_MATS = {
    "ref_band_a": (0.30, 0.32, 0.38, 1.0),
    "ref_band_b": (0.20, 0.21, 0.26, 1.0),
    "ref_slice":  (0.95, 0.72, 0.20, 1.0),   # SLICE / ROOM boundaries
    "ref_mark":   (0.35, 0.80, 0.95, 1.0),   # posture heights
    "ref_spec":   (0.90, 0.35, 0.35, 1.0),   # the inherited 1.96 m spec line
    "ref_gu":     (0.45, 0.85, 0.55, 1.0),   # the GU footprint
}


def log(m):
    print("[P8-SCENE] %s" % m)


def ref_material(key):
    if key in bpy.data.materials:
        return bpy.data.materials[key]
    m = bpy.data.materials.new(key)
    m.use_nodes = False
    m.diffuse_color = REF_MATS[key]
    return m


def collection(name):
    c = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(c)
    return c


def move_to(ob, coll):
    for c in list(ob.users_collection):
        c.objects.unlink(ob)
    coll.objects.link(ob)


def slab(name, centre, size, mat_key):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=centre)
    ob = bpy.context.active_object
    ob.name = name
    ob.scale = Vector(size)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    ob.data.materials.append(ref_material(mat_key))
    return ob


def label(name, text, location, size=0.055, mat_key="ref_mark"):
    """Text in the scene rather than in a README. A ruler whose lines are not
    named is a decoration."""
    bpy.ops.object.text_add(location=location)
    ob = bpy.context.active_object
    ob.name = name
    ob.data.body = text
    ob.data.size = size
    # (90, 0, 180) and not (90, 0, 0), for two reasons that happen to share one
    # rotation. CAM_FRONT sits at +Y looking toward -Y, so text left at 90 alone
    # faces AWAY and renders mirrored. And in that view screen-right is world -X
    # while Blender text extends along local +X, so it would also read
    # right-to-left. The extra 180 about Z fixes the facing and the reading
    # direction together.
    ob.rotation_euler = (math.radians(90.0), 0.0, math.radians(180.0))
    ob.data.materials.append(ref_material(mat_key))
    return ob


def build_scale_reference(coll):
    """A voxel ruler standing behind the figure, plus the floor footprint."""
    made = []
    # BEHIND the figure, not beside it. At x = -0.46 the ruler sat inside the
    # 1.76 m T-pose arm span and crossed the body in every view.
    y_wall = -0.55
    x_wall = 0.0
    band_w, band_d = 0.30, 0.02
    # Labels hang off the ruler's screen-RIGHT edge, which is world -X.
    lbl_x = -(band_w * 0.5) - 0.03

    n_bands = int(round(ROOM_M / VOXEL_M))          # 16 voxels = one room
    for i in range(n_bands):
        z0 = i * VOXEL_M
        made.append(slab("ref_voxel_%02d" % i,
                         (x_wall, y_wall, z0 + VOXEL_M * 0.5),
                         (band_w, band_d, VOXEL_M * 0.94),
                         "ref_band_a" if i % 2 == 0 else "ref_band_b"))

    # SLICE and ROOM lines — heavier and wider than a voxel band, because §4.7b's
    # whole correction was that a slice is HALF a room and the two were confused.
    for z, txt in ((GU_M, "SLICE  8 vox  1.60 m"), (ROOM_M, "ROOM  16 vox  3.20 m")):
        made.append(slab("ref_line_%s" % txt.split()[0].lower(),
                         (x_wall, y_wall - 0.012, z),
                         (band_w * 1.5, 0.03, 0.012), "ref_slice"))
        made.append(label("lbl_%s" % txt.split()[0].lower(), txt,
                          (lbl_x, y_wall - 0.04, z + 0.018),
                          size=0.05, mat_key="ref_slice"))

    # Posture heights (§4.7), measured and gated — not suggestions.
    for z, txt in ((1.80, "BODY  9.0 vox  1.80 m"),
                   (1.10, "crouch  5.5 vox"),
                   (0.44, "prone  2.2 vox")):
        made.append(slab("ref_mark_%s" % txt.split()[0].lower(),
                         (x_wall, y_wall - 0.008, z),
                         (band_w * 1.25, 0.024, 0.009), "ref_mark"))
        made.append(label("lbl_%s" % txt.split()[0].lower(), txt,
                          (lbl_x, y_wall - 0.04, z + 0.018), size=0.05))

    # The inherited spec line, drawn in its own colour because it is the one
    # number on this ruler that is NOT a constraint — see the module docstring.
    made.append(slab("ref_mark_spec", (x_wall, y_wall - 0.008, 1.96),
                     (band_w * 1.25, 0.024, 0.009), "ref_spec"))
    made.append(label("lbl_spec", "1.96 m  <- S2 mockup's hat, not a constraint",
                      (lbl_x, y_wall - 0.04, 1.978),
                      size=0.042, mat_key="ref_spec"))

    # One GAME UNIT on the floor: the footprint the figure has to live inside.
    t = 0.012
    for dx, dy, sx, sy in ((0, GU_M / 2, GU_M, t), (0, -GU_M / 2, GU_M, t),
                           (GU_M / 2, 0, t, GU_M), (-GU_M / 2, 0, t, GU_M)):
        made.append(slab("ref_gu_edge_%.2f_%.2f" % (dx, dy),
                         (dx, dy, 0.002), (sx, sy, 0.004), "ref_gu"))
    made.append(label("lbl_gu", "1 GU  1.60 m",
                      (GU_M * 0.46, -GU_M * 0.5 - 0.06, 0.02),
                      size=0.052, mat_key="ref_gu"))

    for ob in made:
        move_to(ob, coll)
        ob.hide_select = True       # reference, never sculpted by accident
        ob.hide_render = True       # never in a bake
    log("scale reference: %d objects (voxel ruler, SLICE/ROOM, postures, GU)"
        % len(made))


def add_camera(name, elev_deg, azim_deg, ortho, target, coll, dist=10.0):
    cam_data = bpy.data.cameras.new(name)
    cam_data.type = "ORTHO"
    cam_data.ortho_scale = ortho
    cam = bpy.data.objects.new(name, cam_data)
    bpy.context.scene.collection.objects.link(cam)
    e, a = math.radians(elev_deg), math.radians(azim_deg)
    cam.location = Vector((
        target.x + dist * math.cos(e) * math.sin(a),
        target.y - dist * math.cos(e) * math.cos(a),
        dist * math.sin(e) + target.z,
    ))
    cam.rotation_euler = (target - cam.location).to_track_quat("-Z", "Y").to_euler()
    move_to(cam, coll)
    return cam


def main():
    base.reset_scene()

    rig_coll = collection("RIG")
    blocking_coll = collection("BLOCKING")
    scale_coll = collection("SCALE")
    cam_coll = collection("CAMERAS")

    arm, z = base.build_armature()
    segs = base.build_segments(z)
    base.bind_rigid(arm, segs)
    base.add_sockets(arm, z)
    height, span = base.sanity_checks(arm, segs, z)

    move_to(arm, rig_coll)
    for ob in bpy.data.objects:
        if ob.type == "EMPTY" and ob.name.startswith("socket_"):
            move_to(ob, rig_coll)
    arm.show_in_front = True        # the rig has to be visible through the body

    for _, ob in segs:
        move_to(ob, blocking_coll)
        # Locked, not hidden: a shape to work against and overwrite, never one to
        # sculpt by accident.
        ob.hide_select = True
        ob.hide_render = True

    build_scale_reference(scale_coll)

    target = Vector((0.0, 0.0, 0.96))
    game_cam = add_camera("CAM_GAME", GAME_ELEV, GAME_AZIM, 2.15, target, cam_coll)
    add_camera("CAM_FRONT", 0.0, 180.0, 3.10, target, cam_coll)
    add_camera("CAM_SIDE", 0.0, 90.0, 2.15, target, cam_coll)
    add_camera("CAM_BACK", 0.0, 0.0, 3.10, target, cam_coll)
    bpy.context.scene.camera = game_cam

    # Ship size, so F12 is a one-key reality check rather than a separate tool.
    sc = bpy.context.scene
    sc.render.engine = "BLENDER_WORKBENCH"
    sc.render.resolution_x = int(round(SHIP_PX * 420.0 / 620.0))
    sc.render.resolution_y = SHIP_PX
    sc.render.film_transparent = True
    sc.render.image_settings.file_format = "PNG"
    sc.render.image_settings.color_mode = "RGBA"
    sc.display.shading.light = "STUDIO"
    sc.display.shading.color_type = "MATERIAL"

    # The ratified palette, present so colours are picked from it rather than
    # invented and reconciled later.
    for key in base.MATS:
        base.material(key)

    os.makedirs(OUT_DIR, exist_ok=True)
    bpy.ops.wm.save_as_mainfile(filepath=OUT_BLEND)

    log("collections: RIG (armature + %d sockets) · BLOCKING (%d locked parts) · "
        "SCALE · CAMERAS" % (7, len(segs)))
    log("render set to %dx%d from CAM_GAME — F12 is the real in-game size"
        % (sc.render.resolution_x, sc.render.resolution_y))
    log("palette preloaded: %s" % ", ".join(sorted(base.MATS)))
    log("blocking body measures %.3f m; BODY line at 1.80 m, spec line at 1.96 m"
        % height)
    log("wrote %s" % os.path.relpath(OUT_BLEND, base.REPO_ROOT))


if __name__ == "__main__":
    main()
