# AUTO-GENERATED by godot/scripts/tools/build_tileset.gd
# Re-run the builder whenever tiles are added or renamed.
# Maps tile_name strings to TileSet source_ids.
class_name TileRegistry
extends RefCounted

const TILES: Dictionary = {
	"floor_NE": 0,
	"floor_NW": 1,
	"floor_SE": 2,
	"floor_SW": 3,
}
