# AUTO-GENERATED by godot/scripts/tools/build_tileset.gd
# Re-run the builder whenever tiles are added or renamed.
# Maps tile_name strings to TileSet source_ids.
class_name TileRegistry
extends RefCounted

const TILES: Dictionary = {
	"block_NE": 0,
	"block_NW": 1,
	"block_SE": 2,
	"block_SW": 3,
	"floor_NE": 4,
	"floor_NW": 5,
	"floor_SE": 6,
	"floor_SW": 7,
	"wallCornerHalf_NE": 8,
	"wallCornerHalf_NW": 9,
	"wallCornerHalf_SE": 10,
	"wallCornerHalf_SW": 11,
	"wallCorner_NE": 12,
	"wallCorner_NW": 13,
	"wallCorner_SE": 14,
	"wallCorner_SW": 15,
	"wallFace_NE": 16,
	"wallFace_NW": 17,
	"wallFace_SE": 18,
	"wallFace_SW": 19,
	"wallHalf_NE": 20,
	"wallHalf_NW": 21,
	"wallHalf_SE": 22,
	"wallHalf_SW": 23,
	"wall_NE": 24,
	"wall_NW": 25,
	"wall_SE": 26,
	"wall_SW": 27,
	"subcube_concrete": 28,
	"subcube_metal": 29,
	"subcube_stone": 30,
	"subcube_wood": 31,
}
