extends Node2D
## Room controller — M1 prototype
##
## Responsibilities:
##   - Load the TileSet generated by build_tileset.gd
##   - Build the tile name→source_id registry at startup
##   - Populate TileMapLayer nodes with a test room layout
##
## TileMapLayer nodes expected as children:
##   FloorLayer     — walkable floor tiles  (y_sort_enabled = false)
##   StructureLayer — walls, obstacles, props (y_sort_enabled = true)


@onready var floor_layer:     TileMapLayer = $FloorLayer
@onready var structure_layer: TileMapLayer = $StructureLayer
@onready var camera:          Camera2D     = $Camera2D

## tile_name → TileSet source_id  (built from TileSet custom data at startup)
var tiles: Dictionary = {}

const TILESET_PATH := "res://godot/resources/tilesets/tileset_blocks.tres"


func _ready() -> void:
	var tile_set: TileSet = load(TILESET_PATH)
	if tile_set == null:
		push_error("TileSet not found at %s — run build_tileset.gd first." % TILESET_PATH)
		return

	floor_layer.tile_set     = tile_set
	structure_layer.tile_set = tile_set

	_build_registry(tile_set)
	_make_test_room(9, 9)

	# Center camera on room
	var room_center := _cell_to_world(Vector2i(4, 4), tile_set.tile_size)
	camera.position = room_center


## Build name→id lookup from TileSet custom data.
## Runs once at startup; fast even with 240 tiles.
func _build_registry(tile_set: TileSet) -> void:
	for i in tile_set.get_source_count():
		var sid := tile_set.get_source_id(i)
		var src := tile_set.get_source(sid) as TileSetAtlasSource
		if src == null:
			continue
		var td := src.get_tile_data(Vector2i(0, 0), 0)
		if td:
			tiles[td.get_custom_data("tile_name")] = sid
	print("[Room] Registry built: %d tiles loaded." % tiles.size())


## Place a single tile on a layer. Logs a warning for unknown names.
func place(layer: TileMapLayer, cell: Vector2i, tile_name: String) -> void:
	var sid: int = tiles.get(tile_name, -1)
	if sid == -1:
		push_warning("[Room] Unknown tile: '%s'" % tile_name)
		return
	layer.set_cell(cell, sid, Vector2i(0, 0))


## Generate a simple rectangular test room (W×H cells).
## Border → block_N walls. Interior → floor_N tiles.
func _make_test_room(W: int, H: int) -> void:
	for x in range(W):
		for y in range(H):
			var cell := Vector2i(x, y)
			var is_border := (x == 0 or x == W - 1 or y == 0 or y == H - 1)
			if is_border:
				place(structure_layer, cell, "block_N")
			else:
				place(floor_layer, cell, "floor_N")
	print("[Room] Test room generated: %d×%d." % [W, H])


## Convert a TileMap cell coordinate to world position (for camera centering).
func _cell_to_world(cell: Vector2i, tile_size: Vector2i) -> Vector2:
	# Isometric (diamond-down) offset formula
	return Vector2(
		(cell.x - cell.y) * tile_size.x / 2.0,
		(cell.x + cell.y) * tile_size.y / 2.0
	)
